name: WakaTime Update

on:
  schedule:
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update README with metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # Credentials
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Flags
          COMMIT_MESSAGE: "Update README statistics"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
